name: deploy

on:
  push:
    branches:
      - main
      - develop

env:
  ECR_REPOSITORY: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credencials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: amazon-ecr-login

      - name: Determine image tag
        id: determine-image-tag
        run: |
          echo ::set-output name=image-tag::$(echo ${{ github.sha }} | cut -c -7)

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.amazon-ecr-login.outputs.registry }}
        run: |
          docker build . \
            --target prod-runner \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.determine-imae-tag.outputs.image-tag }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.determine-imae-tag.outputs.image-tag }}
